### ISSUE TITLE
State of Nodejs (tracking)

### ISSUE THREAD

**Issue by hsjobeki** [nix-community/dream2nix#830]
# State of the Ecosystem

As of today there are no "easy to use" nodejs plug-n-play solutions that both work out of the box, but also provide the important feature of deeply overriding dependencies and modifying the overall build process.

## Features 

This list may contain all base requirements that are fundamentally important.

- [ ] Ease of use 
- [ ] Override
  - [ ] Modify the build of the parent (build phases, node version, ... )
  - [ ] Modify dependencies 
    - [ ] unpack phase
    - [ ] enable/disable/alter lifecycle scripts
    - [ ] Source Override (e.g. with custom derivation)
- [ ] Support to debug and find problems fast

This list may be extended and checked against the state of the WIP-node-v3 module.

**Comment by adrian-gierakowski** [comment]
@hsjobeki I wonder if any work has been recently done towards this? Also is [this](https://github.com/nix-community/dream2nix/tree/main/modules/dream2nix/WIP-nodejs-builder-v3) the WIP module you are referring to? Thanks!
